
title: xDj4
logo: /assets/img/logo.png
description: -xDj4-.
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
# theme: jekyll-theme-minima
# theme: jekyll-theme-architect

header_pages:
  - about.md
